Repository microsoft/hlsl-specs, pull requests merged in 2025-03, with the labels that each got.

#410 [0029] Fix link to the API proposal
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#418 Super minor updates to cooperative-vector.md
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#417 Fix broken links and a few minor formatting issues in hlsl-long-vector-type.md
  proposals/0026-hlsl-long-vector-type.md
Labels: needs-triage

#377 [OMM] Remove validation masking, update spec
  proposals/0024-opacity-micromaps.md
Labels: needs-triage

#409 [0029] Extend ComponentType for interpretations
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#415 [0029] Use "SignedOpKind" enum to indict input/ouput vector signedness
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#422 Add stride alignment, FP8 details, fix VectorMatrix to MatrixVector...
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#424 [0029] Fix some typos, add link to API proposal
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#425 [0029] Rename COOPERATIVE_VECTOR D3D APIs to LINEAR_ALGEBRA
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#426 [0029] Clarify matrix/bias alignment and size restrictions, rename reducesumaccumulate to vectoraccumulate
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#34 [0007] Big update to flesh out const instance methods
  proposals/0007-const-instance-methods.md
  proposals/0007-const-member-functions.md
Labels: needs-triage, Design Meeting

#325 [202y] Propose adding C++11-style constructors
  proposals/0031-constructors.md
Labels: needs-triage, Design Meeting

#435 2025-03-18 Design Meeting Agenda & Minutes
  docs/DesignMeetingMinutes/2025-03-18.md
Labels: Design Meeting

#429 [0029] Use consistent n-byte aligned notation
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#434 [0029] Fix some stale type names / typos in Coop Vec D3D API example
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#440 Pesky typo in 0026-hlsl-long-vector-type.md
  proposals/0026-hlsl-long-vector-type.md
Labels: needs-triage

#436 [NFC] Add .gitattributes and renormalize
  .gitattributes
  SUPPORT.md
  docs/HLSL202x.md
  docs/Process.md
  proposals/0002-cxx-attributes.md
  proposals/0003-numeric-constants.md
  proposals/0004-unions.md
  proposals/0005-strict-initializer-lists.md
  proposals/0006-reference-types.md
  proposals/0007-const-member-functions.md
  proposals/0008-non-member-operator-overloading.md
  proposals/0009-math-modes.md
  proposals/0017-conforming-literals.md
  proposals/0020-hlsl-202x-202y.md
  proposals/0023-cxx11-base.md
  proposals/0028-dxil18.md
  proposals/0031-constructors.md
  proposals/templates/basic-template.md
  proposals/templates/infrastructure-template.md
Labels: needs-triage

#445 Run pdflatex twice
  specs/language/CMakeLists.txt
Labels: language-spec

#443 [0029] Fix ComponentType numbering comments
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#439 [0031] Add Initial proposal for cooperative vectors API
  proposals/0031-hlsl-vector-matrix-operations.md
Labels: needs-triage

#382 [SER] Add CommittedCustomHitKind to HitObject::FromRayQuery
  proposals/0027-shader-execution-reordering.md
Labels: needs-triage

#452 Renumber HLSL constructors proposal to 32
  proposals/0032-constructors.md
Labels: needs-triage

#453 [SER] Specify how reordercoherent is encoded
  proposals/0027-shader-execution-reordering.md
Labels: needs-triage

#447 [0029] Define commandList interactions for LinearAlgebraConvertMatrix() [no HLSL/DXIL impact]
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#430 [0029] Clarify 16-byte underlying allocation requirement
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#456 [0029] Fix parameter ordering
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#464 [0029] Fix broken links
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#463 [0029] Fix sample code tier check
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#454 [0029] Fix description of OuterProductAccumulate
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#466 Remove validation mask language, update spec given implementation knowledge
  proposals/0024-opacity-micromaps.md
Labels: needs-triage

#450 [0031] Add builtins
  proposals/0031-hlsl-vector-matrix-operations.md
Labels: needs-triage
