Repository microsoft/hlsl-specs, pull requests merged in 2025-02, with the labels that each got.

#77 [SM6.8] Add proposal for DXIL 1.8
  proposals/0028-dxil18.md
Labels: Requires Shader Model, Design Meeting

#361 Rework hlsl-vector-type into two specs
  proposals/0026-hlsl-long-vector-type.md
  proposals/0026-hlsl-vector-type.md
  proposals/NNNN-dxil-vectors.md
Labels: Design Meeting

#390 [0029] Cooperative Vectors: add proposal
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#396 Number proposal 30
  proposals/0030-dxil-vectors.md
Labels: needs-triage

#397 [0029] Set cooperative vectors proposal to under review
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#401 [0031] Add strawman proposal for HLSL Vector Matrix Operations
  proposals/0031-hlsl-vector-matrix-operations.md
Labels: needs-triage

#398 [0029] Remove HLSL API from Cooperative Vector proposal
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#407 [0029] Clarifying behavior for atomic operations, OOB access of Matrix and Bias Buffers.
  proposals/0029-cooperative-vector.md
Labels: needs-triage
