Repository microsoft/hlsl-specs, pull requests merged in 2025-05, with the labels that each got.

#419 Constant buffers language spec - initial draft
  specs/language/declarations.tex
  specs/language/resources.tex
Labels: language-spec, needs-triage

#483 [0029] Make "input signed op kind"s be "is input unsigned" and booleans
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#343 [202x] Propose adding vk::SampledTexture* types
  proposals/0034-vk-sampled-texture.md
Labels: needs-triage, Design Meeting

#499 First pass at validator backcompat testing proposal
  proposals/infra/INF-0005-validator-backcompat-testing.md
Labels: needs-triage

#469 [Decl.Init.Agg] Arrays of unknown size
  specs/language/declarations.tex
Labels: language-spec
