Repository microsoft/hlsl-specs, pull requests merged in 2025-04, with the labels that each got.

#65 [0002] Specify the grammar formulations for attributes
  proposals/0002-assets/AttributeGrammarRender.png
  proposals/0002-assets/ClassGrammarRender.png
  proposals/0002-assets/StatementGrammarRender.png
  proposals/0002-cxx-attributes.md
Labels: needs-triage, Design Meeting

#391 [202x][202y] Update proposals for correct targets
  proposals/0001-hlsl-namespace.md
  proposals/0002-cxx-attributes.md
  proposals/0004-unions.md
  proposals/0005-strict-initializer-lists.md
  proposals/0006-reference-types.md
  proposals/0008-non-member-operator-overloading.md
  proposals/0009-math-modes.md
  proposals/0020-hlsl-202x-202y.md
  proposals/0022-hlsl-loop-unroll-factor.md
Labels: needs-triage

#392 2025-02-18 Design Meeting Agenda & Minutes
  docs/DesignMeetingMinutes/2025-02-18.md
Labels: Design Meeting

#468 [0029] Rename optimal matrix layouts to match operations
  proposals/0029-cooperative-vector.md
Labels: needs-triage

#451 [0031] Add MatrixRef, VectorRef, Vector, Mul, MulAdd, OuterProductAccumulate, VectorAccumulate
  proposals/0031-hlsl-vector-matrix-operations.md
Labels: needs-triage

#475 [0027] Remove HitObject_ObjectToWorld4x3 and HitObject_WorldToObject4x3
  proposals/0027-shader-execution-reordering.md
Labels: needs-triage

#473 [0027] Put SER HLSL additions under dx namespace.
  proposals/0027-shader-execution-reordering.md
Labels: needs-triage

#470 Add a DXIL 1.9 summary proposal
  proposals/NNNN-dxil19.md
Labels: needs-triage

#486 [0033] Assign DXIL 1.9 proposal number 0033
  proposals/0033-dxil19.md
Labels: needs-triage

#494 [0029][0031]Add Matrix Layout constraint to OuterProductOptimal for OuterProductAccumulate function
  proposals/0029-cooperative-vector.md
  proposals/0031-hlsl-vector-matrix-operations.md
Labels: needs-triage

#481 [0030][SM6.9] Add list of ops with vector overload
  proposals/0030-dxil-vectors.md
Labels: needs-triage

#472 [0029] Update example code to use real API
  proposals/0029-cooperative-vector.md
Labels: needs-triage
